stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load impi
    - export I_MPI_SHM_LMT=shm
    - source ~/python_virtualenv/bin/activate
    - pip show numpy
  script:
    - pytest pygyro -m serial -k 'not long' --short
    - make
    - coverage run -p --source=pygyro -m pytest pygyro -m serial
    - coverage combine
    - mpirun -n 1 coverage run -p mpi_tester.py pygyro -m parallel --mpisub
    - coverage combine -a
    - mpirun -n 4 coverage run -p mpi_tester.py pygyro -m parallel --mpisub
    - coverage combine -a
    - mpirun -n 6 coverage run -p mpi_tester.py pygyro -m parallel --mpisub
    - coverage combine -a
    - mpirun -n 20 coverage run -p mpi_tester.py pygyro -m parallel --mpisub
    - coverage combine -a
    - python checkCoverage.py
  after_script:
    - make clean
    - deactivate
    - module unload impi
