stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load impi
    - export I_MPI_SHM_LMT=shm
    - source ~/python_virtualenv/bin/activate
    - pip show numpy
  script:
    - python pygyro/splines/spline_eval_funcs.py
    - pytest pygyro -m serial
    - pytest pygyro -m parallel
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 1"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 4"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 6"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 20"
  after_script:
    - rm pygyro/splines/*.so
    - deactivate
    - module unload impi
