stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load anaconda/3
    - module load impi
    - pip show numpy
  script:
    - py.test pygyro -m serial
    - python3 mpi_tester.py pygyro -m parallel
  after_script:
    - echo $?
    - module unload anaconda
    - module unload impi
