stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load impi
    - export I_MPI_SHM_LMT=shm
    - source ~/python_virtualenv/bin/activate
    - pip show numpy
  script:
    - cd pygyro/splines
    - gfortran  -fPIC -O3  -c   mod_context_1.f90
    - f2py -c  --opt='-O3'  -m  spline_eval_funcs spline_eval_funcs.f90 mod_context_1.o
    - cd ../..
    - pytest pygyro -m serial
    - pytest pygyro -m parallel
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 1"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 4"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 6"
    - python mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 20"
  after_script:
    - rm pygyro/splines/*.so
    - rm pygyro/splines/mod_context.o
    - deactivate
    - module unload impi
