stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load anaconda/3
    - module load impi
    - pip show numpy
    - h5cc -showconfig
    - export I_MPI_SHM_LMT=shm
  script:
    - py.test pygyro -m serial
    - py.test pygyro -m parallel
    - python3 mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 1"
    - python3 mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 4"
    - python3 mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 6"
    - python3 mpi_tester.py pygyro -sxvm parallel --mpirun="mpirun -n 20"
  after_script:
    - module unload anaconda
    - module unload impi
