stages:
  - test

testimony:
  stage: test
  tags:
    - vm_linux
  before_script:
    - module load impi
    - export I_MPI_SHM_LMT=shm
    - source ~/python_virtualenv/bin/activate
    - pip show numpy
  script:
    - make
    - pytest pygyro -m serial
    - python checkCoverage.py
    - python mpi_tester.py pygyro -m parallel --mpirun="mpirun -n 1"
    - python mpi_tester.py pygyro -m parallel --mpirun="mpirun -n 4"
    - python mpi_tester.py pygyro -m parallel --mpirun="mpirun -n 6"
    - python mpi_tester.py pygyro -m parallel --mpirun="mpirun -n 20"
  after_script:
    - make clean
    - deactivate
    - module unload impi
